[versions]
ktx = "1.10.0"
kotlin = "1.8.10"
kotlinxCoroutines = "1.6.4"
daggerHilt = "2.44"
daggerHiltCompose = "1.0.0"
okhttp = "4.10.0"
retrofit = "2.9.0"
androidGradlePlugin = "8.0.1"
moshi = "1.14.0"
androidxLifecycle = "2.5.1"
sqlcipher = "4.5.4"
timber = "5.0.1"
constraint = "2.1.4"
lifecycle = "2.2.0"
appcompat = "1.6.1"
fragmentKtx = "1.5.5"
room = "2.5.0"
material_version = "1.9.0"
junit_version = "4.13.2"
test_ext_version = "1.1.5"
espresso_version = "3.5.1"
joda_time_version = "2.12.5"
chuker_version = "3.5.2"
core_version = "1.9.0"
hiltCompilerVersion = "2.44"
crypto_version = "1.1.0-alpha06"
paging3_version = "3.1.1"
viewpager_version = "1.0.0"
picasso_version = "2.8"
rxjava_version = "2.2.21"
rxandroid_version = "2.1.1"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraint = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
dagger-hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "daggerHilt" }
dagger-hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "daggerHiltCompose" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltCompilerVersion" }
dagger-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHilt" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-coroutines = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlcipher = { group = "net.zetetic", name = "android-database-sqlcipher", version.ref = "sqlcipher" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "crypto_version" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
junit = { group = "junit", name = "junit", version.ref = "junit_version" }
test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "test_ext_version" }
test-espresso-core=  { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_version" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging3_version" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging3_version" }
joda-time = { group = "joda-time", name = "joda-time", version.ref = "joda_time_version" }
androidxcore = { group = "androidx.core", name = "core", version.ref = "core_version" }
chucker = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chuker_version" }
chucker-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chuker_version" }
material = { group = "com.google.android.material", name = "material", version.ref = "material_version" }
androidx-room-rxjava = { group = "androidx.room", name = "room-rxjava2", version.ref = "room" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version = "1.1.5" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager_version" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso_version" }
rxreactive-java = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxjava_version" }
rxreactive-android = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxandroid_version" }

[plugins]
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidx-navigation = { id = "androidx.navigation.safeargs.kotlin" }
ktlint-jlleitschuh = { id = "org.jlleitschuh.gradle.ktlint" }



